#!/usr/bin/python3
# Logchain Verification Agent Version 1.0
import os, sys, argparse, requests, threading, json, tarfile, logging, shutil
from datetime import datetime
from py_essentials import hashing as hs

def Load_Logchain_API_Configuration():

    try:
        logging.info(f"{str(datetime.now())} Loading API configuration data.")

        with open(Configuration_File) as JSON_File:
            Configuration_Data = json.load(JSON_File)

            if Configuration_Data['api']['host'] and Configuration_Data['api']['port']:
                return Configuration_Data['api']

            else:
                return None

    except Exception as e:
        logging.warning(f"{str(datetime.now())} {str(e)}.")
        sys.exit()

def API_Check(File, Full_File, API_Data, Backup_File):

    def Check(File, Full_File, API_Data, Backup_File):

        try:
            State = 0
            Host = f"{API_Data['host']}:{str(int(API_Data['port']))}/chain"
            Response = requests.get(Host, verify=API_Data['verify_ssl']).text
            Response = json.loads(Response)

            if 'chain' in Response:

                for Transactions in Response['chain']:

                    if Transactions.get('transactions') and Transactions.get('transactions') != []:

                        for Transaction in Transactions['transactions']:

                            if Transaction['backup'] == Backup_File and Transaction['log_file'] == File:

                                if Transaction['data_hash'] == hs.fileChecksum(Full_File, "sha256"):
                                    return 2

                                else:
                                    return 1

                        return State

        except Exception as e:
            print(e)

    Result = Check(File, Full_File, API_Data, Backup_File)

    if Result == 2:
        logging.info(f"{str(datetime.now())} Successfully verified {File} against the Logchain ledger.")

    elif Result == 1:
        logging.warning(f"{str(datetime.now())} {File} was found in the Logchain ledger but the checksum did not match. This backup appears to have been tampered with.")

    elif Result == 0:
        logging.info(f"{str(datetime.now())} {File} was not found in the Logchain ledger, if you are sure this backup was created by the Logchain Backup Agent, then it could still be in the current block which has not been mined yet.")

    else:
        logging.warning(f"{str(datetime.now())} Unable to get valid response from ledger.")

def Extract(File, Directory):

    try:
        tar = tarfile.open(File, "r:gz")
        tar.extractall(Directory)
        tar.close()
        return True

    except:
        return False

if __name__ == '__main__':

    try:
        logging.basicConfig()
        logging.getLogger().setLevel(logging.INFO)
        Configuration_File = os.path.join(os.path.dirname(os.path.realpath('__file__')), 'config/agent/config.json')
        Parser = argparse.ArgumentParser(description='Tool used to verify backup logs against the Logchain Distributed Ledger.')
        Parser.add_argument('-t', '--tarfile', type=str, help='This option is used to specify a .tar.gz backup file, generated by the Logchain Backup Agent, which contents you desire to verify against the Logchain Distributed Ledger. To run. ./Verify.py -t /var/log/backup/backup.tar.gz')
        Arguments = Parser.parse_args()

        if Arguments.tarfile:
            API_Data = Load_Logchain_API_Configuration()

            if Arguments.tarfile.endswith('.tar.gz'):
                Temp_Directory = '/tmp/Logchain/verify'

                if os.path.exists(Temp_Directory):
                    shutil.rmtree(Temp_Directory)

                os.makedirs(Temp_Directory)
                Decompressed = Extract(Arguments.tarfile, Temp_Directory)

                if Decompressed:

                    for File in os.listdir(Temp_Directory):
                        Full_File = Temp_Directory + "/" + File
                        Thread = threading.Thread(target=API_Check, args=(File, Full_File, API_Data, Arguments.tarfile))
                        Thread.start()

                else:
                    logging.warning(f"{str(datetime.now())} Failed to decompress the provided file.")
                    sys.exit()

            else:
                logging.warning(f"{str(datetime.now())} Please provide a valid tar file with gzip compression (.tar.gz file).")
                sys.exit()

        else:
            logging.warning(f"{str(datetime.now())} No arguments supplied.")
            sys.exit()

    except Exception as e:
        logging.warning(f"{str(datetime.now())} {str(e)}.")
        sys.exit()